steps:
  # Test Connectivity with Cloud SQL (Postgres)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    timeout: 240s
    entrypoint: 'bash'
    args:
    - '-c'
    - |-
      apt-get update -y
      apt-get install postgresql-client -y
      PGPASSWORD='!QAZ2wsx' psql -h 34.79.94.226 -U postgres -w
  options:
  pool:
    name: 'projects/225324244167/locations/europe-west1/workerPools/test-workerpool'
