timeout: 3600s
steps:
  # --- Setup
  - name: node:16
    entrypoint: yarn
    args: [
      'install'
    ]
  - name: node:16
    entrypoint: yarn
    env:
      - 'NODE_ENV=${_NODE_ENV}'
      - 'GOOGLECLOUD_PROJECT=${_GOOGLECLOUD_PROJECT}'
    args: [
      'ts-node',
      'devops/scripts/generateEnvFile.ts'
    ]

      # --- migration  
  - name: node:16
    entrypoint: yarn
    args: [
      'ci:migrate'
    ]

  # --- Build
  - name: node:16
    entrypoint: yarn
    args: [
      'run',
      'contracts:compile'
    ]

  - name: node:16
    entrypoint: yarn
    args: [
      'run',
      'build:functions'
    ]

  - name: node:16
    entrypoint: yarn
    args: [
      'test'
    ]

  - name: 'bash'
    args: [
      'cp',
      '-R',
      './prisma',
      './dist/backend/functions/prisma'
    ]
options:
  pool:
    name: 'projects/225324244167/locations/europe-west6/workerPools/test'
