steps:
  # Test Connectivity with Cloud SQL (Postgres)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    timeout: 240s
    entrypoint: 'bash'
    args:
    - '-c'
    - |-
      apt-get update -y
      apt install inetutils-ping -y
      ping -w 1 10.121.192.3
      apt-get install postgresql-client -y
      PGPASSWORD='!QAZ2wsx' psql -h 10.121.192.3 -U postgres -w

# [START cloudbuild_private_worker_pool]
options:
  pool:
    name: 'projects/225324244167/locations/europe-west1/workerPools/test-workerpool'
